### ISSUE TITLE
Providers and Aliases in app.php

### ISSUE THREAD

**Issue by avxkim** [ivanlemeshev/laravel5-cyrillic-slug#5]
Change service provider to:

`IvanLemeshev\Laravel5CyrillicSlug\SlugServiceProvider::class,`

Alias to:

`'Slug' => IvanLemeshev\Laravel5CyrillicSlug\SlugFacade::class,`

**Comment by chuprik** [comment]
Did you see this https://github.com/ivanlemeshev/laravel5-cyrillic-slug/blob/master/composer.json#L15 ?
